btcusd,btcusd,btc-usd,btc/usd
ethusd,ethusd,eth-usd,eth/usd
xrpusd,xrpusd,xrp-usd,xrp/usd
ltcusd,ltcusd,ltc-usd,ltc/usd
dshusd,dshusd,dsh-usd,dsh/usd
eosusd,eosusd,eos-usd,eos/usd
btceur,btceur,btc-eur,btc/eur
etheur,etheur,eth-eur,eth/eur
ethbtc,ethbtc,eth-btc,eth/btc
ltcbtc,ltcbtc,ltc-btc,ltc/btc